### ISSUE TITLE
Broken environment CI on main

### ISSUE THREAD

**Issue by nathanshammah** [tghp/unitary-fund#38]
Broken environment CI on main, although the PR branch environments were passing fine. Not sure why this is the case. Checking with @WrathfulSpatula and @joshdavenport.

**Comment by joshdavenport** [comment]
No worries on this one @nathanshammah, it's the initial pass of a GitHub pages workflow added to the codebase at the start of the project. This workflow does work well, but is failing now due to a missing env var. This will be all fully setup when migrating to the UF repo. Vercel still deploying fine as seen below.

<img width="612" alt="Screenshot 2023-08-04 at 08 51 07" src="https://github.com/tghp/unitary-fund/assets/757828/4a111bc5-0fc9-496e-9efb-1b6793e66b0d">

If the red X is a pain in the immediate term, do let me know, re-open, and I'll look at disabling the erroring workflow.
